# .github/workflows/md-to-pdf-pandoc.yml
name: build-readme-pdf

on:
  push:
    branches:
      - main
    paths:
      - "docs/README.md"
  workflow_dispatch:

jobs:
  pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:3.1
        with:
          args: >
            docs/README.md
            -o docs/README.pdf
            --from=gfm
            --pdf-engine=xelatex
            --template=eisvogel            # 好みで変更
            --metadata=title:"Project Docs"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: readme-pdf
          path: docs/README.pdf
