# .github/workflows/md-to-pdf-puppeteer.yml
name: build-readme-pdf-with-md-to-pdf

on:
  workflow_dispatch: # 手動トリガだけ。push 連動なら書き換えて

jobs:
  pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf@6 # バージョン固定を推奨

      - name: Generate PDF (no sandbox)
        run: |
          md-to-pdf docs/README.md \
            --launch-options '{"args":["--no-sandbox","--disable-setuid-sandbox"]}'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: readme-pdf
          path: docs/README.pdf
